const indianAirports = [
    { name: "Indira Gandhi International Airport", code: "DEL", state: "Delhi" },
    { name: "Chhatrapati Shivaji Maharaj International Airport", code: "BOM", state: "Maharashtra" },
    { name: "Kempegowda International Airport", code: "BLR", state: "Karnataka" },
    { name: "Chennai International Airport", code: "MAA", state: "Tamil Nadu" },
    { name: "Netaji Subhas Chandra Bose International Airport", code: "CCU", state: "West Bengal" },
    { name: "Rajiv Gandhi International Airport", code: "HYD", state: "Telangana" },
    { name: "Cochin International Airport", code: "COK", state: "Kerala" },
    { name: "Sardar Vallabhbhai Patel International Airport", code: "AMD", state: "Gujarat" },
    { name: "Goa International Airport", code: "GOI", state: "Goa" },
    { name: "Jaipur International Airport", code: "JAI", state: "Rajasthan" },
    { name: "Pune International Airport", code: "PNQ", state: "Maharashtra" },
    { name: "Trivandrum International Airport", code: "TRV", state: "Kerala" },
    { name: "Lucknow Chaudhary Charan Singh International Airport", code: "LKO", state: "Uttar Pradesh" },
    { name: "Srinagar Airport", code: "SXR", state: "Jammu & Kashmir" },
    { name: "Bagdogra Airport", code: "IXB", state: "West Bengal" },
    { name: "Amritsar Sri Guru Ram Dass Jee International Airport", code: "ATQ", state: "Punjab" },
    { name: "Biju Patnaik International Airport", code: "BBI", state: "Odisha" },
    { name: "Madurai Airport", code: "IXM", state: "Tamil Nadu" },
    { name: "Varanasi Lal Bahadur Shastri International Airport", code: "VNS", state: "Uttar Pradesh" },
    { name: "Mangalore International Airport", code: "IXE", state: "Karnataka" },
    { name: "Visakhapatnam International Airport", code: "VTZ", state: "Andhra Pradesh" },
    { name: "Nagpur Dr. Babasaheb Ambedkar International Airport", code: "NAG", state: "Maharashtra" },
    { name: "Raipur Swami Vivekananda Airport", code: "RPR", state: "Chhattisgarh" },
    { name: "Dehradun Jolly Grant Airport", code: "DED", state: "Uttarakhand" },
    { name: "Port Blair Veer Savarkar International Airport", code: "IXZ", state: "Andaman and Nicobar Islands" },
    { name: "Agartala Maharaja Bir Bikram Airport", code: "IXA", state: "Tripura" },
    { name: "Dibrugarh Airport", code: "DIB", state: "Assam" },
    { name: "Dimapur Airport", code: "DMU", state: "Nagaland" },
    { name: "Imphal Tulihal Airport", code: "IMF", state: "Manipur" },
    { name: "Jammu Airport", code: "IXJ", state: "Jammu & Kashmir" },
    { name: "Leh Kushok Bakula Rimpochee Airport", code: "IXL", state: "Ladakh" },
    { name: "Gaya Airport", code: "GAY", state: "Bihar" },
    { name: "Patna Jayprakash Narayan Airport", code: "PAT", state: "Bihar" },
    { name: "Ranchi Birsa Munda Airport", code: "IXR", state: "Jharkhand" },
    { name: "Shillong Umroi Airport", code: "SHL", state: "Meghalaya" },
    { name: "Tezpur Airport", code: "TEZ", state: "Assam" },
    { name: "Udaipur Maharana Pratap Airport", code: "UDR", state: "Rajasthan" },
    { name: "Vadodara Airport", code: "BDQ", state: "Gujarat" },
    { name: "Aurangabad Chikkalthana Airport", code: "IXU", state: "Maharashtra" },
    { name: "Kolhapur Airport", code: "KLH", state: "Maharashtra" },
    { name: "Tiruchirappalli International Airport", code: "TRZ", state: "Tamil Nadu" },
    { name: "Tuticorin Airport", code: "TCR", state: "Tamil Nadu" },
    { name: "Coimbatore International Airport", code: "CJB", state: "Tamil Nadu" },
    { name: "Hubli Airport", code: "HBX", state: "Karnataka" },
    { name: "Belgaum Airport", code: "IXG", state: "Karnataka" },
    { name: "Kadapa Airport", code: "CDP", state: "Andhra Pradesh" },
    { name: "Kozhikode Calicut International Airport", code: "CCJ", state: "Kerala" },
    { name: "Kannur International Airport", code: "CNN", state: "Kerala" }
];

module.exports = indianAirports;
